export const DELETE_WAITLIST_GUEST = 'DELETE_WAITLIST_GUEST';
export const NOTIFY_WAITLIST_GUEST = 'NOTIFY_WAITLIST_GUEST';
export const EDIT_WAITLIST_GUEST = 'EDIT_WAITLIST_GUEST';
export const ADD_WAITLIST_GUEST = 'ADD_WAITLIST_GUEST';
