export const DELETE_WAITLIST_GUEST = 'DELETE_WAITLIST_GUEST';
export const NOTIFY_WAITLIST_GUEST = 'NOTIFY_WAITLIST_GUEST';
export const REMEMBER_WAITLIST_VISIT = 'REMEMBER_WAITLIST_VISIT';
export const ADD_WAITLIST_GUEST = 'ADD_WAITLIST_GUEST';
export const UPDATE_WAITLIST_VISIT = 'UPDATE_WAITLIST_VISIT';
export const CREATE_WAITLIST_VISIT = 'CREATE_WAITLIST_VISIT';
export const UPDATE_FREQUENTLY_USED_TAGS = 'Tags/UpdateFrequents';

